# Generated by Django 4.0 on 2022-02-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Roll_no', models.IntegerField()),
                ('English', models.IntegerField()),
                ('Tamil', models.IntegerField()),
                ('Science', models.IntegerField()),
                ('Maths', models.IntegerField()),
                ('Social', models.IntegerField()),
                ('Hindi', models.IntegerField()),
                ('Average', models.IntegerField()),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
    ]
