# Generated by Django 4.0.2 on 2022-02-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=20)),
                ('hero', models.CharField(max_length=20)),
                ('heroine', models.CharField(max_length=20)),
            ],
        ),
    ]
